// Code Generated by Sidekick is for learning and experimentation purposes only.
const express = require("express");
const router = express.Router();
const studentsController = require("../controllers/studentsController");

router.get("/", studentsController.getAllStudents);
router.post("/", studentsController.createStudent);
router.get("/:id", studentsController.getStudentById);
router.put("/:id", studentsController.updateStudent);
router.delete("/:id", studentsController.deleteStudent);

module.exports = router;
