// Code Generated by Sidekick is for learning and experimentation purposes only.
const mongoose = require("mongoose");

const paymentSchema = new mongoose.Schema({
  studentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Student",
    required: true,
  },
  amount: { type: Number, required: true },
  paymentDate: { type: Date, default: Date.now },
  method: String,
  remarks: String,
});

module.exports = mongoose.model("Payment", paymentSchema);
